### ISSUE TITLE
On Search results page if you do a refined search listings images disappear

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion-template-turbosale#2] opened 2016-12-05 04:04 UTC

**Comment by agorshechnikov** [comment] 2017-01-06 04:05
This issue is related to the Turbosale template but it's related to the Autos package.
Fix can be found here: http://www.subrion.org/forums/threads/how-to-enable-make-and-model-search-in-car-page.2400/#post-10634

Bug has already been fixed in upcoming 4.0.3 version of the Autos package.

**Closed as completed by agorshechnikov** 2017-01-06 04:05 UTC

**Comment by AlinCG** [comment] 2017-01-06 23:33
Hi @agorshechnikov. The issue is not related to  http://www.subrion.org/forums/threads/how-to-enable-make-and-model-search-in-car-page.2400/#post-10634  Has nothing to do with adding Make / Model dropdown lists to the Refine Search block. This happens because of ".brazzers-daddy img{ display: none; }" 

http://screencast-o-matic.com/watch/cbV100QzR3

**Comment by oglasi** [comment] 2017-01-08 14:57
Hi @AlinCG do you know how to fix that (http://screencast-o-matic.com/watch/cbV100QzR3)?
Thanks in advance :)

**Comment by AlinCG** [comment] 2017-01-10 22:50
Hi @oglasi  For now the only way is to give up on the nice looking " brazzers-daddy" class.

On list-autos.tpl change line:

{foreach $listing.auto_pictures as $pic}
				{printImage imgfile=$pic['path'] title=$listing.model class='img-responsive' fullimage=false}
			{/foreach}

to

{printImage imgfile=$listing.auto_pictures[0]['path'] title=$listing.model}

and in user-style.css  put:

.g-list .ia-card-hr__image img {
    display: block;
}

**Comment by oglasi** [comment] 2017-01-11 21:40
Thanks @AlinCG,  its works :)
